### ISSUE TITLE
Why does a ParabolicSarIndicator value(n) change over time?

### ISSUE THREAD

**Issue by jamestomk** [ta4j/ta4j-wiki#16]
I am trying to understand how a ParabolicSarIndicator based on TimeSeries can have previous time values change as new Bars are added to the timeSeries.  I'll attach an example.  It would seem that sar(n-1) should only be based on timeseries(0 through (n-1)), yet as I add to the series, previous values change.   It would be like saying: "Sorry, but our StopLoss price should have been some different value back then".

As an example, after I add each bar to the timeSeries, I cache the Sar value to be compared with a sar.getValue(i) at a later time:
[Example.java.txt](https://github.com/ta4j/ta4j-wiki/files/4188712/Example.java.txt)

**Comment by jamestomk** [comment]
the 3am "Aha!" moment hit me this morning; that indeed this indicator is backward looking (needs future data to tell me whether and up/down trend has flipped, and cannot tell me what StopLoss to set in a real-time analysis).   
Is my thinking correct?   As one might spend too much time building an algo that is only useful in backtesting (with pre-loaded timeSeries) but not useful in real-time, is there some documentation that sorts out which indicators are useful for real-time?
Perhaps the question is more how to differentiate indicators that don't "change" the value of getValue(n) when called at 'n' vs. 'n+x'?

**Comment by team172011** [comment]
duplicate https://github.com/ta4j/ta4j/issues/522
