### ISSUE TITLE
Get Max/Min Closeprice for a defined Timeframe?

### ISSUE THREAD

**Issue by brintal** [ta4j/ta4j-wiki#5]
Is there an indicator, that always computes the maximum closeprice of the last x bars?
The number of bars should be configurable.
E.g. what was the maximum close price in the last 60 minutes?

Is there something like this or do I have to implement my own indicator?

**Comment by Pk13055** [comment]
```java
HighestValueIndicator(new ClosePriceIndicator(this.series), timeFrame);
```
